"""Generate a self-signed certificate and output its SHA-256 pin hash."""

import datetime
import hashlib
import os

from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

DAYS_VALID = 3650
SERVER_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SERVER_DIR, "data")
CERT_FILE = os.path.join(OUTPUT_DIR, "cert.pem")
KEY_FILE = os.path.join(OUTPUT_DIR, "key.pem")
CLIENT_PIN_FILE = os.path.join(
    os.path.dirname(SERVER_DIR), "Client", "Lib", "GeneratedCertificatePin.cs"
)


def write_client_pin(cert_hash):
    pin_source = (
        "// Generated by Server/gen_cert.py. Do not edit manually.\n"
        "namespace CSOToolbox.Client.Lib\n"
        "{\n"
        "    internal static class GeneratedCertificatePin\n"
        "    {\n"
        f'        internal const string Sha256 = "{cert_hash}";\n'
        "    }\n"
        "}\n"
    )
    with open(CLIENT_PIN_FILE, "w", encoding="utf-8", newline="\n") as pin_file:
        pin_file.write(pin_source)


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    key = ec.generate_private_key(ec.SECP256R1())

    subject = issuer = x509.Name(
        [
            x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, "CSO"),
            x509.NameAttribute(NameOID.COMMON_NAME, "localhost"),
        ]
    )

    now = datetime.datetime.now(datetime.UTC)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + datetime.timedelta(days=DAYS_VALID))
        .add_extension(
            x509.SubjectAlternativeName([x509.DNSName("localhost")]),
            critical=False,
        )
        .sign(key, hashes.SHA256())
    )

    with open(CERT_FILE, "wb") as f:
        f.write(cert.public_bytes(serialization.Encoding.PEM))
    print(f"Certificate written to {CERT_FILE}")

    key_fd = os.open(KEY_FILE, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(key_fd, "wb") as f:
        f.write(
            key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )
    if os.name == "posix":
        os.chmod(KEY_FILE, 0o600)
    print(f"Private key written to {KEY_FILE}")

    cert_hash = hashlib.sha256(
        cert.public_bytes(serialization.Encoding.DER)
    ).hexdigest()
    print(f"\nSHA-256 pin hash: {cert_hash}")
    write_client_pin(cert_hash)
    print(f"Client pin written to {CLIENT_PIN_FILE}")


if __name__ == "__main__":
    main()
