// Generated by Server/gen_cert.py. Do not edit manually.
namespace CSOToolbox.Client.Lib
{
    internal static class GeneratedCertificatePin
    {
        internal const string Sha256 = "6d4803b43c030e20d89136abdd3503c88aea0e38a422158c4261150dd0bb6ee2";
    }
}
